### PR TITLE
email fix

### PR DESCRIPTION
**Pull request by tyalt1**
I was getting the same issue as @li442il (Chronial/snapraid-runner#4) about email not working. I wanted to put his code into a pull request and see if it works.

### CODE REVIEW

**Comment by Chronial** [comment]
This Pull Request forces TLS onto all SMTP Connections. That is definitely not a solution. This needs to be a config option.

**Comment by Chronial** [comment]
Have you tried just using port 465 with SSL instead?

**Comment by tyalt1** [comment]
I use exactly that port and have SSL set to true in my config file. However it still fails to send the email.

Here is the error log it prints out, if it helps:
2016-03-22 02:04:20,371 [ERROR ] Failed to send email
Traceback (most recent call last):
  File "/opt/snapraid-runner/snapraid-runner.py", line 107, in finish
    send_email(is_success)
  File "/opt/snapraid-runner/snapraid-runner.py", line 96, in send_email
    server.login(config["smtp"]["user"], config["smtp"]["password"])
  File "/usr/lib/python2.7/smtplib.py", line 622, in login
    raise SMTPAuthenticationError(code, resp)
SMTPAuthenticationError: (535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/answer/14257 s9sm13608580qks.42 - gsmtp')

**Comment by Chronial** [comment]
Well, did you click on the link in that message? :)
https://support.google.com/mail/answer/14257

**Comment by tyalt1** [comment]
Yeah, I've tried everything it suggests.

- The "App Password" page no longer exists.
- I've signed into the web version of gmail multiple times.
- I've allowed access with the third link.
- I've allowed access to unsecure apps.

Nothing I try seems to work :(

**Comment by tyalt1** [comment]
After some more testing, I got it working. In my google account settings I need to grant access to "less secure apps" here: https://www.google.com/settings/security/lesssecureapps.

It makes me feel a little nervous, like my account is more vulnerable. However it works so thats good!

**Comment by Chronial** [comment]
You could just use some other provider to send your mail that does not deem "Microsoft Outlook and Mozilla Thunderbird" as insecure :).

**Pull request closed without merging**
