### PR TITLE
added deletethreshold as argument to override config

### PR DESCRIPTION
**Pull request by longranger**

### CODE REVIEW

**Comment by Chronial** [comment]
Thanks for the PR, but what is the use case for this?

**Comment by longranger** [comment]
I never do syncs directly via snapraid.
  - I appreciate the added security of checking number of deleted files
before syncing, added by snapraid-runner
  - I appreciate the consistent logging done through snapraid-runner
    - I currently save the logs with timestamps (via a bash wrapper). I see
you have an issue for that, and I'm working on implementing it, but python
seems a bit frustrating when it comes to timezones.

So, I have deletethreshold set to 20 in my configs, but when I find I have
deleted 50 files, after confirming those deletes make sense, I then run
snapraid-runner, passing it -d 50 as an argument.

Once I get timestamped logs working, I also plan to implement SMART
logging. I currently do that separately via a bash script running smartctl
directly, but I prefer the output from snapraid. My idea is simply to run
snapraid SMART separately, saving it to a separate log. Then compare that
output to the previous log, and if it is identical, delete the new one. If
it is different, archive the old one and email the admin. We could just use
numerically incremented logs for this, relying on metadata for times...
which makes perfect sense, but timestamped logs feels more correct to me
(if redundant).

Sorry for overloading this email, hopefully you see the use.

**Comment by Chronial** [comment]
I would prefer to have a simpler `--deletethreshold / -f` option. I also think that is more intuitive to use.

Would that also adequately solve your use case?

**Comment by Chronial** [comment]
Fixed in #25

**Pull request closed without merging**
